type: rest
testable: true
cors:
  enabled: true
phase: realized
enforced: true
gateway: datapower-api-gateway
properties:
  target-url:
    value: https://echo.websocket.org/
    description: URL du serveur WebSocket publique qui permet de r√©aliser des tests
    encoded: false
assembly:
  execute:
    - websocket-upgrade:
        title: websocket-upgrade
        version: 2.0.0
        verb: keep
        target-url: $(target-url)
        follow-redirects: false
        timeout: 60
        parameter-control:
          type: blocklist
          values: []
        header-control:
          type: blocklist
          values: []
        request-assembly:
          execute: []
        response-assembly:
          execute: []
        inject-proxy-headers: true
application-authentication:
  certificate: false
activity-log:
  enabled: true
  success-content: activity
  error-content: header
